# Generated by Django 4.0.6 on 2022-08-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Expedient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Ex', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=65)),
                ('prioridade', models.CharField(max_length=20)),
                ('confidencial', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=20)),
                ('anexo', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_recepcao', models.DateTimeField(auto_now=True)),
                ('recebido', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('departamento', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.departamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
