# Generated by Django 4.0.6 on 2022-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='assunto',
            field=models.CharField(blank=True, default='Sem Assunto', max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='anexo',
            field=models.FileField(upload_to='expedient/uploads/%Y/%m/%d/'),
        ),
    ]
