# Generated by Django 4.0.6 on 2022-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0002_expedient_assunto_alter_expedient_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
