# Generated by Django 4.0.6 on 2022-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0003_expedient_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='anexo',
            field=models.FileField(null=True, upload_to='expedient/uploads/%Y/%m/%d/'),
        ),
    ]
