# Generated by Django 4.0.6 on 2022-08-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedient', '0004_alter_expedient_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='assunto',
            field=models.CharField(default='sem assunto', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedient',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='departamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.departamento'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=95)),
                ('numero_telefone', models.CharField(max_length=65)),
                ('estado', models.CharField(max_length=50)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.departamento')),
            ],
        ),
    ]
