# Generated by Django 4.0.6 on 2022-09-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedient', '0005_alter_expedient_assunto_alter_expedient_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now=True)),
                ('anexo', models.FileField(null=True, upload_to='expedient/parecer/%Y/%m/%d/')),
                ('id_expedient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.expedient')),
                ('id_receptor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
