# Generated by Django 4.0.6 on 2022-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0006_parecer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
