# Generated by Django 4.0.6 on 2022-10-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0009_parecer_id_emissor_alter_parecer_id_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='id_receptor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.departamento'),
        ),
    ]
