# Generated by Django 4.0.6 on 2022-10-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0010_alter_parecer_id_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='id_emissor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissor', to='expedient.departamento'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='id_receptor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptor', to='expedient.departamento'),
        ),
    ]
