# Generated by Django 4.0.6 on 2024-01-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedient', '0011_alter_parecer_id_emissor_alter_parecer_id_receptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('prazo', models.DateTimeField()),
                ('data_confirmacao_recepcao', models.DateTimeField()),
                ('confirmacao_user_status', models.BooleanField(default=False)),
                ('confirmacao_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.funcionario')),
                ('destinatario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatario', to='expedient.departamento')),
                ('remetente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
