# Generated by Django 4.0.6 on 2024-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0013_alter_protocolo_confirmacao_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='prazo',
            field=models.DateField(),
        ),
    ]
