# Generated by Django 4.0.6 on 2024-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0014_alter_protocolo_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
