# Generated by Django 4.0.6 on 2024-10-13 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedient', '0015_alter_protocolo_data_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('Carta', 'Recebimento de Carta'), ('Reingresso', 'Pedido de Reingresso'), ('Declaracao', 'Pedido de Declaração'), ('Certificado', 'Emissão de Certificado'), ('Monografia', 'Revisão de Monografia'), ('Outra', 'Outra')], max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('prazo', models.DateTimeField(blank=True, help_text='Prazo para conclusão da atividade', null=True)),
                ('hora_inicio', models.TimeField(default=datetime.datetime.now)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('aguardando', 'Aguardando Informações'), ('atrasada', 'Atrasada')], default='progresso', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=10)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('tempo_gasto', models.DurationField(blank=True, help_text='Tempo total gasto na atividade', null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='expedient.funcionario')),
            ],
        ),
    ]
