# Generated by Django 4.0.6 on 2024-10-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0015_alter_protocolo_data_emissao'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_funcionario', to='expedient.funcionario'),
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_atividades', to='expedient.departamento')),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_tipo', to='actividades.tipoatividade'),
        ),
    ]
