# Generated by Django 5.1.3 on 2025-10-19 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_actual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Actual')),
                ('regime_contrato', models.CharField(blank=True, choices=[('Indeterminado', 'Indeterminado'), ('Determinado', 'Determinado')], max_length=50, null=True, verbose_name='Regime de Contrato')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade')),
                ('idioma', models.CharField(blank=True, choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Francês', 'Francês'), ('Línguas Locais', 'Línguas Locais'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Idioma')),
                ('contacto_telefonico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto Telefónico')),
                ('endereco_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço Electrónico')),
                ('endereco_fisico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Físico')),
                ('areas_interesse', models.TextField(blank=True, null=True, verbose_name='Áreas de Interesse')),
                ('ficheiro_cv', models.FileField(blank=True, null=True, upload_to='cv/uploads/%Y/%m/%d/', verbose_name='Ficheiro do CV')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciasDigitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferramentas_trabalho', models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Intermédio', 'Intermédio'), ('Avançado', 'Avançado')], max_length=50, null=True, verbose_name='Uso de ferramentas de trabalho')),
                ('gestao_email', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Gestão de e-mail e comunicação digital')),
                ('uso_plataformas_ensino', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Uso de plataformas de ensino online')),
                ('plataforma_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual plataforma?')),
                ('uso_redes_sociais', models.CharField(blank=True, choices=[('Whatsapp', 'Whatsapp'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn')], max_length=50, null=True, verbose_name='Uso de redes sociais')),
                ('outras_competencias', models.TextField(blank=True, null=True, verbose_name='Outras competências digitais')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencias_digitais', to='rhumanos.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Competência Digital',
                'verbose_name_plural': 'Competências Digitais',
                'ordering': ['curriculo'],
            },
        ),
        migrations.CreateModel(
            name='CursoCertificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Curso / Certificação')),
                ('instituicao_formadora', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instituição Formadora')),
                ('duracao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duração')),
                ('ano_conclusao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_certificacoes', to='rhumanos.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Curso / Certificação',
                'verbose_name_plural': 'Cursos / Certificações',
                'ordering': ['-ano_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_entrada', models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento'), ('Técnico Médio', 'Técnico Médio'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Grau Académico de Entrada')),
                ('grau_actual', models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento'), ('Técnico Médio', 'Técnico Médio'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Grau Académico Actual')),
                ('area_formacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área de Formação')),
                ('instituicao_ensino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instituição de Ensino')),
                ('ano_conclusao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='rhumanos.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Formação Académica',
                'verbose_name_plural': 'Formações Académicas',
                'ordering': ['-ano_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadesTalentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades_tecnicas', models.CharField(blank=True, choices=[('Marcenaria', 'Marcenaria'), ('Alfaiataria', 'Alfaiataria'), ('Mecânica', 'Mecânica'), ('Tecelagem e Bordado', 'Tecelagem e Bordado'), ('Cerâmica', 'Cerâmica'), ('Artesanato', 'Artesanato')], max_length=100, null=True, verbose_name='Habilidades Técnicas')),
                ('habilidades_tecnicas_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro (Habilidades Técnicas)')),
                ('comunicacionais', models.CharField(blank=True, choices=[('Comunicação verbal', 'Comunicação verbal'), ('Comunicação escrita', 'Comunicação escrita'), ('Escuta activa', 'Escuta activa'), ('Negociação e persuasão', 'Negociação e persuasão')], max_length=100, null=True, verbose_name='Habilidades Comunicacionais')),
                ('comunicacionais_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro (Comunicacionais)')),
                ('culturais', models.CharField(blank=True, choices=[('Canto', 'Canto'), ('Dança', 'Dança'), ('Teatro', 'Teatro'), ('Literatura oral', 'Literatura oral'), ('Artes visuais', 'Artes visuais'), ('Uso de instrumentos musicais', 'Uso de instrumentos musicais')], max_length=100, null=True, verbose_name='Habilidades Culturais')),
                ('culturais_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro (Culturais)')),
                ('desportivas', models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Basquetebol', 'Basquetebol'), ('Voleibol', 'Voleibol'), ('Andebol', 'Andebol'), ('Atletismo', 'Atletismo'), ('Ténis', 'Ténis'), ('Natação', 'Natação'), ('Caraté', 'Caraté'), ('Judo', 'Judo'), ('Xadrez', 'Xadrez'), ('Golfe', 'Golfe')], max_length=100, null=True, verbose_name='Habilidades Desportivas')),
                ('gastronomicas', models.CharField(blank=True, choices=[('Culinária local', 'Culinária local'), ('Culinária rápida/fast food', 'Culinária rápida/fast food'), ('Culinária saudável', 'Culinária saudável'), ('Gastronomia nacional', 'Gastronomia nacional'), ('Gastronomia internacional', 'Gastronomia internacional'), ('Confeitaria e Panificação', 'Confeitaria e Panificação'), ('Organização de eventos', 'Organização de eventos')], max_length=100, null=True, verbose_name='Habilidades Gastronômicas / Eventos')),
                ('outras_habilidades', models.TextField(blank=True, null=True, verbose_name='Outras Habilidades e Talentos')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_talentos', to='rhumanos.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Habilidade / Talento',
                'verbose_name_plural': 'Habilidades e Talentos',
                'ordering': ['curriculo'],
            },
        ),
        migrations.CreateModel(
            name='MobilidadeInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Disponibilidade para mobilidade interna')),
                ('area_interesse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área ou departamento de interesse')),
                ('experiencia_anterior', models.TextField(blank=True, null=True, verbose_name='Experiência anterior em mobilidade interna')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilidade_interna', to='rhumanos.curriculo', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Mobilidade Interna',
                'verbose_name_plural': 'Mobilidade Interna',
                'ordering': ['curriculo'],
            },
        ),
    ]
