# Generated by Django 5.1.3 on 2025-10-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhumanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='idioma',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='idiomas',
            field=models.ManyToManyField(blank=True, to='rhumanos.idioma', verbose_name='Idiomas'),
        ),
    ]
