# Generated by Django 5.1.3 on 2025-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhumanos', '0003_competenciasdigitais_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='rhumanos/perfil/%Y/%m/%d/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='grau_actual',
            field=models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento'), ('Técnico Médio', 'Técnico Médio'), ('Ensino Secundário', 'Ensino Secundário'), ('Ensino Básico', 'Ensino Básico'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Grau Académico Actual'),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='grau_entrada',
            field=models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento'), ('Técnico Médio', 'Técnico Médio'), ('Ensino Secundário', 'Ensino Secundário'), ('Ensino Básico', 'Ensino Básico'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Grau Académico de Entrada'),
        ),
    ]
