# Generated by Django 5.1.3 on 2025-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('holiday', 'Feriado'), ('exam', 'Exame'), ('class', 'Aula'), ('break', 'Interrupção')], max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
