# Generated by Django 5.1.3 on 2025-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_remove_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, help_text='Cor HEX para exibir no calendário (ex: #198754)', max_length=20, null=True),
        ),
    ]
