# Generated by Django 4.0.6 on 2024-03-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacao',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
