# Generated by Django 4.0.6 on 2024-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_ocupacao_dia_semana_alter_ocupacao_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacao',
            name='tempo',
            field=models.IntegerField(choices=[(1, '1º tempo'), (2, '2º tempo'), (3, '3º tempo'), (4, '4º tempo')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='estado',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='faculdade',
            field=models.CharField(choices=[('FCJ', 'FCJ'), ('FCES', 'FCES'), ('FCT', 'FCT')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=25),
        ),
    ]
