# Generated by Django 5.1.3 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('curso', models.CharField(blank=True, max_length=150, null=True)),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('faculdade', models.CharField(blank=True, choices=[('FCS', 'FCS'), ('FG', 'FG'), ('FCT', 'FCT')], max_length=3, null=True)),
                ('faixa_etaria', models.CharField(blank=True, choices=[('16-35', '16 - 35 anos'), ('36-45', '36 - 45 anos'), ('46+', '46 anos ou mais')], max_length=5, null=True)),
                ('situacao_profissional', models.CharField(blank=True, choices=[('ESTUDANTE', 'Estudante'), ('ESTUDANTE_TRABALHADOR', 'Estudante Trabalhador')], max_length=30, null=True)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º'), (5, '5º'), (6, '6º'), (7, '7º'), (8, '8º')], null=True)),
                ('bairro_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_identificacao_curso', models.BooleanField(blank=True, null=True)),
                ('motivo_influencia_familiar', models.BooleanField(blank=True, null=True)),
                ('motivo_oportunidade', models.BooleanField(blank=True, null=True)),
                ('motivo_ja_trabalha_area', models.BooleanField(blank=True, null=True)),
                ('motivo_localizacao_udm', models.BooleanField(blank=True, null=True)),
                ('motivo_outro', models.CharField(blank=True, max_length=255, null=True)),
                ('escolha_udm_identificacao', models.BooleanField(blank=True, null=True)),
                ('escolha_udm_indicacao_familiar', models.BooleanField(blank=True, null=True)),
                ('escolha_udm_valor_propina', models.BooleanField(blank=True, null=True)),
                ('escolha_udm_indicacao_servicos', models.BooleanField(blank=True, null=True)),
                ('escolha_udm_localizacao', models.BooleanField(blank=True, null=True)),
                ('escolha_udm_outro', models.CharField(blank=True, max_length=255, null=True)),
                ('conheceu_panfletos', models.BooleanField(blank=True, null=True)),
                ('conheceu_radio', models.BooleanField(blank=True, null=True)),
                ('conheceu_televisao', models.BooleanField(blank=True, null=True)),
                ('conheceu_jornal', models.BooleanField(blank=True, null=True)),
                ('conheceu_portal_udm', models.BooleanField(blank=True, null=True)),
                ('conheceu_facebook_udm', models.BooleanField(blank=True, null=True)),
                ('conheceu_familiar_amigo', models.BooleanField(blank=True, null=True)),
                ('conheceu_secretaria', models.BooleanField(blank=True, null=True)),
                ('conheceu_outro', models.CharField(blank=True, max_length=255, null=True)),
                ('suporte_despesas', models.CharField(blank=True, choices=[('PROPRIO', 'Encarregado Próprio'), ('BOLSA', 'Bolsa'), ('EMPRESTIMO', 'Empréstimo'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('expectativas_curso', models.TextField(blank=True, null=True)),
                ('receios_curso', models.TextField(blank=True, null=True)),
                ('avaliacao_apresentacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avaliacao_conhecimento_curso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avaliacao_conhecimento_udm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avaliacao_fluencia_comunicativa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avaliacao_objetivos_pessoais', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contacto_estudante_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_estudante_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_encarregado_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('entrevistado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('data_entrevista', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrevista do Estudante',
                'verbose_name_plural': 'Entrevistas dos Estudantes',
                'ordering': ['-data_entrevista'],
            },
        ),
    ]
