# Generated by Django 5.1.3 on 2026-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='faculdade',
            field=models.CharField(blank=True, choices=[('FCES', 'Faculdade de Ciências Económicas e Sociais'), ('FCJ', 'Faculdade de Ciências Jurídicas'), ('FCT', 'Faculdade de Ciências Tecnológicas')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='suporte_despesas',
            field=models.CharField(blank=True, choices=[('PROPRIO', 'Encargo Próprio'), ('ENCARREGADO', 'Encarregado'), ('BOLSA', 'Bolsa'), ('EMPRESTIMO', 'Empréstimo'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
    ]
