# Generated by Django 5.1.3 on 2026-01-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0002_alter_entrevistaestudante_faculdade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_facebook_udm',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_familiar_amigo',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_jornal',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_outro',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_panfletos',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_portal_udm',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_radio',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_secretaria',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='conheceu_televisao',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_identificacao',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_indicacao_familiar',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_indicacao_servicos',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_localizacao',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_outro',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='escolha_udm_valor_propina',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_identificacao_curso',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_influencia_familiar',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_ja_trabalha_area',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_localizacao_udm',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_oportunidade',
        ),
        migrations.RemoveField(
            model_name='entrevistaestudante',
            name='motivo_outro',
        ),
        migrations.AddField(
            model_name='entrevistaestudante',
            name='como_conheceu_udm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaestudante',
            name='motivo_escolha_curso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaestudante',
            name='motivo_escolha_udm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='faculdade',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='faixa_etaria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='semestre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='situacao_profissional',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistaestudante',
            name='suporte_despesas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
