# Generated by Django 5.1.3 on 2026-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0003_remove_entrevistaestudante_conheceu_facebook_udm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaestudante',
            name='data_entrevista_por',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaestudante',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
