# Generated by Django 5.1.3 on 2026-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0004_entrevistaestudante_data_entrevista_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaestudante',
            name='escola',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
