# Generated by Django 5.1.3 on 2025-10-08 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(blank=True, default=None, help_text='Data em que o funcionário marcou a presença.', null=True, verbose_name='Data da Presença')),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora exata em que o funcionário registou a presença.', null=True, verbose_name='Hora de Entrada')),
                ('origem_registo', models.CharField(blank=True, default=None, help_text='Origem do registo de presença (fixo: dispositivo biométrico Hikvision).', max_length=50, null=True, verbose_name='Origem do Registo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registo foi criado no sistema.', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registo.', verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(blank=True, help_text='Funcionário que registou a presença no dispositivo biométrico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-data_presenca', 'hora_entrada'],
                'indexes': [models.Index(fields=['usuario'], name='formatura_p_usuario_f47627_idx'), models.Index(fields=['data_presenca'], name='formatura_p_data_pr_decc03_idx')],
            },
        ),
    ]
