# Generated by Django 5.1.3 on 2025-11-09 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0015_alter_protocolo_data_emissao'),
        ('formatura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formatura',
                'verbose_name_plural': 'Formaturas',
                'ordering': ['-data', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PontoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(blank=True, default=0, help_text='Define a sequência de apresentação do ponto de agenda', null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, null=True)),
                ('prioridade', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('percentual', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='formaturas/anexos/')),
                ('aprovado', models.BooleanField(default=False)),
                ('comentario_avaliador', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_agenda', to='expedient.departamento')),
                ('formatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_agenda', to='formatura.formatura')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponto de Agenda',
                'verbose_name_plural': 'Pontos de Agenda',
                'ordering': ['ordem', '-prioridade', 'titulo'],
            },
        ),
    ]
