# Generated by Django 5.1.3 on 2025-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatura', '0003_formatura_atualizado_por_formatura_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoagenda',
            name='ordem',
            field=models.CharField(blank=True, help_text='Define a sequência usando letras (ex.: A, B, C...)', max_length=5, null=True),
        ),
    ]
