# Generated by Django 4.0.6 on 2024-09-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedient', '0015_alter_protocolo_data_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante_nome', models.CharField(max_length=100)),
                ('avaliacao_nome', models.CharField(choices=[('teste_1', 'Teste 1'), ('teste_2', 'Teste 2'), ('exame', 'Exame'), ('exame_recorrencia', 'Exame de Recorrência')], max_length=100)),
                ('data_avaliacao', models.DateField()),
                ('autorizado', models.BooleanField(blank=True, default=False, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_autorizacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedient.funcionario')),
            ],
        ),
    ]
