# Generated by Django 4.0.6 on 2024-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
