from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    #path('', views.dashbord, name='dashbord'),
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashbord/', views.dashbord, name='dashbord'),
    #path('dashbord/expedient/<int:id>/edit/', views.dashbord_expedient_edit, name='dashbord_expedient_edit'),
    #path('dashbord/expedient/<int:id>/see/', views.dashbord_expedient_see, name='dashbord_expedient_see'),
    path('dashbord/expedient/new', views.dashbord_expedient_new,
         name='dashbord_expedient_new'),
    path('dashbord/expedient/emitidos', views.dashbord_expedient_emitidos,
         name='dashbord_expedient_emitidos'),
    path('dashbord/expedient/recebidos', views.dashbord_expedient_recebidos,
         name='dashbord_expedient_recebidos'),
    path('dashbord/expedient/recebidos_funcionario', views.dashbord_expedient_recebidos_funcionario,
         name='dashbord_expedient_recebidos_funcionario'),
    path('dashbord/expedient/encaminhados_funcionario', views.dashbord_expedient_encaminhados_funcionario,
         name='dashbord_expedient_encaminhados_funcionario'),
    path('dashbord/expedient/encaminhados_submetidos_funcionario', views.dashbord_expedient_encaminhados_submetidos_funcionario,
         name='dashbord_expedient_encaminhados_submetidos_funcionario'),
    path('dashbord/expedient/<int:id>/detail/',
         views.dashbord_expedient_detail,
         name='dashbord_expedient_detail'),
    path('dashbord/expedient/<int:id>/user/',
         views.dashbord_expedient_ver_user,
         name='dashbord_expedient_ver_user'),
    #path('dashbord/expedient/<int:id>/parecer/<str:tipo>', views.dashbord_expedient_parecer, name='dashbord_expedient_parecer'),
    path('dashbord/expedient/<int:id>/parecer/responder',
         views.dashbord_expedient_parecer_responder, name='dashbord_expedient_parecer_responder'),
    path('dashbord/expedient/<int:id>/parecer/encaminhar',
         views.dashbord_expedient_parecer_encaminhar, name='dashbord_expedient_parecer_encaminhar'),
    path('dashbord/expedient/respondidos_funcionario', views.dashbord_expedient_respondidos_funcionario,
         name='dashbord_expedient_respondidos_funcionario'),
    path('dashboard/expedient/search/', views.search, name="search"),
    path('dashboard/expedient/secretaria/search/',
         views.secretaria_search, name="secretaria_search"),

    path('dashbord/protocol/new', views.dashbord_protocol_new,
         name='dashbord_protocol_new'),
    path('dashbord/protocol/emitidos', views.dashbord_protocol_emitidos,
         name='dashbord_protocol_emitidos'),
    path('dashbord/protocol/emitidos/pendente', views.dashbord_protocol_emitidos_pendente,
         name='dashbord_protocol_emitidos_pendente'),
    path('dashbord/protocol/emitidos/finalizado', views.dashbord_protocol_emitidos_finalizado,
         name='dashbord_protocol_emitidos_finalizado'),
    path('dashbord/protocol/recebidos', views.dashbord_protocol_recebidos,
         name='dashbord_protocol_recebidos'),
    path('dashbord/protocol/<int:id>/detail/',
         views.dashbord_protocol_detail,
         name='dashbord_protocol_detail'),
    path('dashbord/protocol/<int:id>/confirmation/',
         views.dashbord_protocol_confirmacao,
         name='dashbord_protocol_confirmacao'),
    path('dashboard/protocol/search/',
         views.protocol_search, name="protocol_search"),
    path('dashboard/protocol/statistics/',
         views.protocol_statistics, name="protocol_statistics"),
#     path('dashboard/protocol/statisticsd/',
#          views.protocol_statisticsd, name="protocol_statisticsd"),
    path('dashboard/protocol/gargalos/', views.relatorio_gargalos_view, name='relatorio_gargalos'),

]
