# Generated by Django 5.1.3 on 2025-11-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('lugares_reservados', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=20, null=True)),
                ('codigo_convite', models.CharField(blank=True, max_length=20, null=True)),
                ('presente_em', models.DateTimeField(blank=True, help_text='Hora em que o convidado foi registado como presente', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='convite.evento')),
            ],
        ),
    ]
