# Generated by Django 5.1.3 on 2025-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='codigo_estudante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
