# Generated by Django 5.1.3 on 2025-03-22 08:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('semestre', models.IntegerField(blank=True, choices=[(1, '1º Semestre'), (2, '2º Semestre')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.faculdade'),
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='pautas/uploads/%Y/%m/%d/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('ativo', models.BooleanField(blank=True, default=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_criadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.disciplina')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPauta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('arquivo', models.TextField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ativo', models.BooleanField(blank=True, default=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pautas.disciplina')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pautas.semestre')),
            ],
            options={
                'verbose_name': 'historical pauta',
                'verbose_name_plural': 'historical pautas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
