# Generated by Django 5.1.3 on 2025-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0002_historicalpauta_avaliacao_pauta_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpauta',
            name='docente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='docente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
