# Generated by Django 5.1.3 on 2025-03-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0003_historicalpauta_docente_pauta_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='faculdade',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.AddField(
            model_name='historicalpauta',
            name='curso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pautas.curso'),
        ),
        migrations.AddField(
            model_name='historicalpauta',
            name='faculdade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pautas.faculdade'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.curso'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pautas.faculdade'),
        ),
    ]
