# Generated by Django 5.1.3 on 2025-03-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0004_remove_curso_faculdade_remove_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='pautas.faculdade'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='pautas.curso'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pautas.curso'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pautas.disciplina'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pautas.faculdade'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pautas.semestre'),
        ),
    ]
